### ISSUE TITLE
Getting server domain/address/subdomain doesn't work

### ISSUE THREAD

**Issue by pythoncat1** [DarkCat09/python-aternos#104]
When trying to access `atserver.domain`, `atserver.subdomain`, or `atserver.address` this error happens:
```
Traceback (most recent call last):
  File "c:\Users\pcat1\Programs\aternos\start.py", line 10, in <module>
    print(srvs[1].subdomain)
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\pcat1\AppData\Roaming\Python\Python311\site-packages\python_aternos\atserver.py", line 277, in subdomain
    atdomain = self.domain
               ^^^^^^^^^^^
  File "C:\Users\pcat1\AppData\Roaming\Python\Python311\site-packages\python_aternos\atserver.py", line 311, in domain
    return self._info['ip']
           ~~~~~~~~~~^^^^^^
KeyError: 'ip'
```

**Comment by mqopi** [comment]
same

**Comment by broseraf228** [comment]
I have the same problem

**Comment by fedehc** [comment]
Same here.
