### ISSUE TITLE
python_aternos.aterrors.CredentialsError: Unable to parse TOKEN from the page

### ISSUE THREAD

**Issue by rimgro** [DarkCat09/python-aternos#15]
`Ignoring exception in command startserver:
Traceback (most recent call last):
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\venv\lib\site-packages\python_aternos\atconnect.py", line 33, in parse_token
    token_func = js_code[1] if len(js_code) > 1 else js_code[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\main.py", line 52, in startserver
    await start_server()
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\main.py", line 24, in start_server
    aternos = Client.from_credentials(config.ATERNOS_USERNAME, config.ATERNOS_PASSWORD)
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\venv\lib\site-packages\python_aternos\__init__.py", line 47, in from_credentials
    return cls.from_hashed(username, md5)
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\venv\lib\site-packages\python_aternos\__init__.py", line 23, in from_hashed
    atconn.parse_token()
  File "C:\Users\rimgro\PycharmProjects\aternos-utils\venv\lib\site-packages\python_aternos\atconnect.py", line 39, in parse_token
    raise CredentialsError(
python_aternos.aterrors.CredentialsError: Unable to parse TOKEN from the page`

**Comment by rimgro** [comment]
The only thing I can notice is that I live in Russia where advertising does not work and because of this, anti-adblock works, but the problem remains on Heroku (US servers)

**Comment by DarkCat09** [comment]
Thanks. I know about the error.  
As I said in #14, the problem is that Aternos has changed a bit the structure of the page, and the regexp can't match a <script> with token.  
Please, wait a while, I'll release the fix tomorrow at about 10:30 GMT+4.

**Comment by DarkCat09** [comment]
Disabling detecting is not needed. The module successfully parses pages because adblock ckecks in JavaScript, executed on client side (in browser).

***

And I've found what causes this error. CloudScraper often can't pass the DDoS-protection and `requests` returns Cloudflare's "Please Wait" title instead of the normal Aternos page.
![Screenshot](https://i.ibb.co/56VgHGz/Screenshot-20220427-212650.png)

**Comment by rimgro** [comment]
Thanks for the help!

**Comment by JimmyTheGreat1500** [comment]
Has it been patched?

**Comment by TheKEIKO** [comment]
Did you find a solution to the problem?
