### ISSUE TITLE
Unable to parse TOKEN from the page (Replit)

### ISSUE THREAD

**Issue by BluePlattypus** [DarkCat09/python-aternos#44]
**My Code:**
```
import discord, asyncio, requests, os
from python_aternos import Client, atwss
from discord.utils import get
from discord.ext import commands

aternos = Client.from_credentials(os.environ['USERNAME'], os.environ['PASSWORD'])
server = aternos.list_servers()[0]
socket = server.wss()

bot = commands.Bot(command_prefix=".")
token = os.environ['TOKEN']
webhook = os.environ['WEBHOOK']
error_handler = "on"

async def socket_connect():
    server.start()
    await asyncio.gather(
        socket.connect()
    )

@bot.command(name = "start")
async def on_message(ctx):
    role = discord.utils.get(ctx.guild.roles, name="🚀︱SMP Member")
    if role in ctx.author.roles:
        embed = discord.Embed()
        embed.set_thumbnail(url = "https://i.ibb.co/QMKR4g1/milky-way-1f30c.png")
        embed.add_field(name = "Server wird gestartet!", value = "Um die Server-Logs zu sehen geh bitte in <#1003277632852463696>.", inline = False)
        embed.set_footer(text = f"Requested by {ctx.message.author.name}.", icon_url = ctx.author.avatar_url)
        await ctx.send(embed = embed)
        await socket_connect()

    elif error_handler == "on":
        embed = discord.Embed('Du brauchst die Rolle\u2000"🚀︱SMP Member" um dieß zu tun!', color = discord.Color.from_rgb((220, 44, 68)))
        embed.set_thumbnail(url = "https://images.emojiterra.com/twitter/512px/274c.png")
        await ctx.send(embed = embed)

@bot.command(name = "status")
async def on_message(ctx):
    role = discord.utils.get(ctx.guild.roles, name="🚀︱SMP Member")
    if role in ctx.author.roles:
        if server.status == "online":
            embed = discord.Embed()
            embed.set_thumbnail(url = "https://i.ibb.co/QMKR4g1/milky-way-1f30c.png")
            embed.add_field(name = "Server Status:", value = "Der Server ist Online.", inline = False)
            embed.set_footer(text = f"Requested by {ctx.message.author.name}.", icon_url = ctx.author.avatar_url)
            await ctx.send(embed = embed)

        if server.status == "offline":
            embed = discord.Embed()
            embed.set_thumbnail(url = "https://i.ibb.co/QMKR4g1/milky-way-1f30c.png")
            embed.add_field(name = "Server Status:", value = 'Der Server ist Offline, um ihn zu starten schreibe ".start" in <#1002498426023465010>.', inline = False)
            embed.set_footer(text = f"Requested by {ctx.message.author.name}.", icon_url = ctx.author.avatar_url)
            await ctx.send(embed = embed)

    elif error_handler == "on":
        embed = discord.Embed(title = "Error:", description = 'Du brauchst die Rolle\u2000"🚀︱SMP Member" um dieß zu tun!', color = discord.Color.from_rgb(220, 44, 68))
        embed.set_thumbnail(url = "https://images.emojiterra.com/twitter/512px/274c.png")
        await ctx.send(embed = embed)

@socket.wssreceiver(atwss.Streams.console)
async def console(msg):
    msg = msg.replace('[K', '').replace('[m', '').replace('>....', '').replace('[?1h=[?2004h', '').replace('[38;2;85;255;85m', '').replace('[33;1m', '').replace('[38;2;255;255;85m', '').replace('[38;2;0;170;0m-', '')

    data = {
    "content" : f"```{msg}```",
    }
    
    requests.post(webhook, json = data)

bot.run(token)
```

**Error:**
```
Traceback (most recent call last):
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 33, in parse_token
    token_func = js_code[1] if len(js_code) > 1 else js_code[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    aternos = Client.from_credentials(os.environ['USERNAME'], os.environ['PASSWORD'])
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/__init__.py", line 47, in from_credentials
    return cls.from_hashed(username, md5)
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/__init__.py", line 23, in from_hashed
    atconn.parse_token()
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 39, in parse_token
    raise CredentialsError(
python_aternos.aterrors.CredentialsError: Unable to parse TOKEN from the page
```

**Comment by DarkCat09** [comment]
Fixed in `v1.1.2`. Please, update.

Error occured due to incorrect 403 status processing and Cloudflare bypassing issues (#25).
