### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://aternos.org/go/ (Replit)

### ISSUE THREAD

**Issue by BluePlattypus** [DarkCat09/python-aternos#45]
**My Code:**
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    aternos = Client.from_credentials(os.environ['USERNAME'], os.environ['PASSWORD'])
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atclient.py", line 86, in from_credentials
    return cls.from_hashed(username, md5)
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atclient.py", line 52, in from_hashed
    atconn.parse_token()
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 46, in parse_token
    loginpage = self.request_cloudflare(
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 247, in request_cloudflare
    return self.request_cloudflare(
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 263, in request_cloudflare
    req.raise_for_status()
  File "/home/runner/Aternos-Bot/venv/lib/python3.8/site-packages/requests/models.py", line 1022, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://aternos.org/go/
```

**Comment by DarkCat09** [comment]
403 means "Unable to bypass Cloudflare protection".
