### ISSUE TITLE
ValueError in random string generator

### ISSUE THREAD

**Issue by DarkCat09** [DarkCat09/python-aternos#56]
I've recently run unit tests and have found a bug in `generate_aternos_rand` function.  
It raised a ValueError exception.

To reproduce the bug, just call random string generator in an endless loop:

```python
>>> from python_aternos import AternosConnect
>>> conn = AternosConnect()
>>> while True:
...     a = conn.generate_aternos_rand()
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/darkcat09/code/python-aternos/python_aternos/atconnect.py", line 128, in generate_aternos_rand
    rand_alphanum = self.convert_num(rand, 36) + ('0' * 17)
  File "/home/darkcat09/code/python-aternos/python_aternos/atconnect.py", line 154, in convert_num
    num = int(sliced)
ValueError: invalid literal for int() with base 10: '7897404767541758e-05'
>>>
```

The problem is in the generator algorithm.  
It was copied from Aternos JavaScript code without any checks.  
So, the function must be rewritten.

**Comment by DarkCat09** [comment]
Fixed in https://github.com/DarkCat09/python-aternos/commit/154b2c2d662bfadd7d564de48d4f22a37b3901b3
