### ISSUE TITLE
Unable to parse TOKEN from the page (Replit)

### ISSUE THREAD

**Issue by Hugo5898** [DarkCat09/python-aternos#58]
Traceback (most recent call last):
  File "/home/runner/DiscordBot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 44, in parse_token
    token_func = js_code[1] if len(js_code) > 1 else js_code[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    aternos = Client.from_credentials(user, pswd)
  File "/home/runner/DiscordBot/venv/lib/python3.8/site-packages/python_aternos/__init__.py", line 47, in from_credentials
    return cls.from_hashed(username, md5)
  File "/home/runner/DiscordBot/venv/lib/python3.8/site-packages/python_aternos/__init__.py", line 23, in from_hashed
    atconn.parse_token()
  File "/home/runner/DiscordBot/venv/lib/python3.8/site-packages/python_aternos/atconnect.py", line 50, in parse_token
    raise CredentialsError(
python_aternos.aterrors.CredentialsError: Unable to parse TOKEN from the page

pls help

**Comment by DarkCat09** [comment]
Do you still have this problem?

**Comment by DarkCat09** [comment]
On my PC, token is parsed successfully.  
On Replit, python-aternos doesn't save session cookies.

**Comment by Hugo5898** [comment]
> Do you still have this problem?

Yes, but it only appears sometimes

**Comment by DarkCat09** [comment]
@Hugo5898, I can help only if you update python-aternos and send the logs.

Also, please, write these lines at the beginning of .py file, above all the code:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
