### ISSUE TITLE
ServerStartError

### ISSUE THREAD

**Issue by GiveMeFox** [DarkCat09/python-aternos#79]
```
Traceback (most recent call last):
  File "/home/sadperson/tests/aternos/main.py", line 8, in <module>
    server.start()
  File "/home/sadperson/.local/lib/python3.11/site-packages/python_aternos/atserver.py", line 161, in start
    raise ServerStartError(error)
python_aternos.aterrors.ServerStartError: ('Sorry, an error occured!', 'Unable to start server, code: Sorry, an error occured!')
```

**Comment by Supslike** [comment]
you might have to enable the eula prompt first, I fixed mine by starting the server in the aternos website and accepted eula prompt. This happens when its a new server

**Comment by DarkCat09** [comment]
> you might have to enable the eula prompt first, I fixed mine by starting the server in the aternos website and accepted eula prompt. This happens when its a new server

@Supslike, oh, thanks, I'll check it and fix EULA auto-accepting.

@GiveMeFox, execute `server.eula()` before starting.
