### ISSUE TITLE
400 error at /players

### ISSUE THREAD

**Issue by Dqsaa** [DarkCat09/python-aternos#89]
`Traceback (most recent call last):
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "main.py", line 184, in whitelist
    whitelist.add(player)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/python_aternos/atplayers.py", line 101, in add
    self.atserv.atserver_request(
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/python_aternos/atconnect.py", line 282, in request_cloudflare
    req.raise_for_status()
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://aternos.org/ajax/players/add.php?TOKEN=

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'whitelist' raised an exception: HTTPError: 400 Client Error: Bad Request for url: https://aternos.org/ajax/players/add.php?TOKEN=
ERROR:discord.app_commands.tree:Ignoring exception in command 'whitelist'
Traceback (most recent call last):
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "main.py", line 184, in whitelist
    whitelist.add(player)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/python_aternos/atplayers.py", line 101, in add
    self.atserv.atserver_request(
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/python_aternos/atconnect.py", line 282, in request_cloudflare
    req.raise_for_status()
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://aternos.org/ajax/players/add.php?TOKEN=`

**Comment by DarkCat09** [comment]
@Dqsaa,

Hello. Please, add these lines to the beginning of your code and send me all output:
```python
from python_aternos import atlog
atlog.set_debug(True)
```

**Comment by Dqsaa** [comment]
@DarkCat09 

Hello, thanks for replying. Here's the full traceback

`2023-07-03 18:00:54,299 DEBUG Restoring session from /home/runner/.at_testingdiscord
2023-07-03 18:00:54,300 DEBUG Adding server DDUoPqO4wt5TaaIM
2023-07-03 18:00:54,300 DEBUG Adding server tOMlf8Ufwd7bq7Q6
/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/tzlocal/unix.py:192: UserWarning: Can not find any timezone configuration, defaulting to UTC.
  warnings.warn("Can not find any timezone configuration, defaulting to UTC.")
2023-07-03 18:00:54,566 DEBUG Requesting(GET)https://aternos.org/go/
2023-07-03 18:00:54,566 DEBUG headers={}
2023-07-03 18:00:54,566 DEBUG params={}
2023-07-03 18:00:54,566 DEBUG data={}
2023-07-03 18:00:54,566 DEBUG req-cookies={'ATERNOS_SESSION': 'wWs'}
2023-07-03 18:00:54,567 DEBUG session-cookies={}
2023-07-03 18:00:55,332 DEBUG AternosConnect received: <!DOCTYPE html>
<html class="account-layout">
<head>
    <meta ch
2023-07-03 18:00:55,332 INFO GET completed with 200 status
2023-07-03 18:00:55,380 DEBUG Requesting(POST)https://aternos.org/ajax/account/login
2023-07-03 18:00:55,380 DEBUG headers={'X-Requested-With': 'XMLHttpRequest'}
2023-07-03 18:00:55,380 DEBUG params={'TOKEN': '0qLUlzH1lbk1LelSxhcf', 'SEC': '17h15tp8ryl00000:i9t2wfaczmq00000'}
2023-07-03 18:00:55,380 DEBUG data={'user': 'testingdiscord', 'password': '815ba69119c953f877ca489d958334fb'}
2023-07-03 18:00:55,380 DEBUG req-cookies={'ATERNOS_SESSION': 'wWs'}
2023-07-03 18:00:55,380 DEBUG session-cookies={'ATERNOS_LANGUAGE': 'en', 'ATERNOS_SEC_17h15tp8ryl00000': 'i9t'}
2023-07-03 18:00:55,948 DEBUG AternosConnect received: {"success":true,"error":null,"data":{"show2FA":false}}
2023-07-03 18:00:55,948 INFO POST completed with 200 status
2023-07-03 18:00:55,949 DEBUG Saving session to /home/runner/.at_testingdiscord
2023-07-03 18:00:55 INFO     discord.client logging in using static token
2023-07-03 18:00:56 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 28dded5efb06cf93be09674548a7d6ca).
Bot is up!
2023-07-03 18:01:09,605 DEBUG Requesting(GET)https://aternos.org/server
2023-07-03 18:01:09,606 DEBUG headers={}
2023-07-03 18:01:09,606 DEBUG params={}
2023-07-03 18:01:09,606 DEBUG data={}
2023-07-03 18:01:09,606 DEBUG req-cookies={'ATERNOS_SERVER': 'DDU', 'ATERNOS_SESSION': 'k5U'}
2023-07-03 18:01:09,606 DEBUG session-cookies={'ATERNOS_LANGUAGE': 'en', 'ATERNOS_SEC_17h15tp8ryl00000': 'i9t'}
2023-07-03 18:01:10,487 DEBUG AternosConnect received: <!DOCTYPE html>
<html>
<head>
    <script type="text/javascript" 
2023-07-03 18:01:10,488 INFO GET completed with 200 status
2023-07-03 18:01:10,916 DEBUG Requesting(POST)https://aternos.org/ajax/players/add.php
2023-07-03 18:01:10,916 DEBUG headers={'X-Requested-With': 'XMLHttpRequest'}
2023-07-03 18:01:10,916 DEBUG params={'TOKEN': '0qLUlzH1lbk1LelSxhcf', 'SEC': '17h15tp8ryl00000:i9t2wfaczmq00000'}
2023-07-03 18:01:10,916 DEBUG data={'list': 'whitelist', 'name': 'babhinav'}
2023-07-03 18:01:10,917 DEBUG req-cookies={'ATERNOS_SERVER': 'DDU', 'ATERNOS_SESSION': 'k5U'}
2023-07-03 18:01:10,917 DEBUG session-cookies={'ATERNOS_LANGUAGE': 'en', 'ATERNOS_SEC_17h15tp8ryl00000': 'i9t'}
2023-07-03 18:01:11,358 DEBUG AternosConnect received: {"success":false,"error":"Unknown method.","data":null}
2023-07-03 18:01:11,359 INFO POST completed with 400 status
2023-07-03 18:01:11 ERROR    discord.app_commands.tree Ignoring exception in command 'whitelist'
Traceback (most recent call last):
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 828, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "main.py", line 183, in whitelist
    whitelist.add(player)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/python_aternos/atplayers.py", line 101, in add
    self.atserv.atserver_request(
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/python_aternos/atconnect.py", line 282, in request_cloudflare
    req.raise_for_status()
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://aternos.org/ajax/players/add.php?TOKEN=0qLUlzH1lbk1LelSxhcf&SEC=17h15tp8ryl00000%3Ai9t2wfaczmq00000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/runner/aternos-start-bot/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'whitelist' raised an exception: HTTPError: 400 Client Error: Bad Request for url: https://aternos.org/ajax/players/add.php?TOKEN=0qLUlzH1lbk1LelSxhcf&SEC=17h15tp8ryl00000%3Ai9t2wfaczmq00000
  `

**Comment by DarkCat09** [comment]
I think it's `/ajax/players/add`, not `add.php`  
Thanks a lot, expect the bugfix tomorrow.

**Comment by Dqsaa** [comment]
I just tried that by missing with the library and it returns the same "success" false

**Comment by DarkCat09** [comment]
Fixed, update to the latest version:
```bash
pip install -U python-aternos
```
