### ISSUE TITLE
Unable to start server.

### ISSUE THREAD

**Issue by petikwastaken** [DarkCat09/python-aternos#92]
Traceback (most recent call last):
  File "c:\Users\Joe\Desktop\aternosbot\main.py", line 10, in <module>
    s.start()
  File "C:\Users\Joe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\python_aternos\atserver.py", line 161, in start
    raise ServerStartError(error)
python_aternos.aterrors.ServerStartError: ('Sorry, an error occured!', 'Unable to start server, code: Sorry, an error occured!')

**Comment by petikwastaken** [comment]
and i got banned

**Comment by DarkCat09** [comment]
> and i got banned

https://github.com/DarkCat09/python-aternos/issues/94#issuecomment-1662561339
