### ISSUE TITLE
Error in Client()

### ISSUE THREAD

**Issue by rawnullbyte** [DarkCat09/python-aternos#96]
So, i used this example:
from python_aternos import Client

atclient = Client()
aternos = atclient.account
atclient.login_with_session('my session id')

srvs = aternos.list_servers()

for srv in srvs:
    print()
    print('***', srv.servid, '***')
    srv.fetch()
    print(srv.domain)
    print(srv.motd)
    print('*** Status:', srv.status)
    print('*** Full address:', srv.address)
    print('*** Port:', srv.port)
    print('*** Name:', srv.subdomain)
    print('*** Minecraft:', srv.software, srv.version)
    print('*** IsBedrock:', srv.edition == atserver.Edition.bedrock)
    print('*** IsJava:', srv.edition == atserver.Edition.java)

print()

and when i run i got this error:
Traceback (most recent call last):
  File "E:\5B5P Bot", line 49, in <module>
    atclient = Client()
TypeError: Client.__init__() missing 1 required positional argument: 'atconn'
[Finished in 710ms]

**Comment by AndrexYT** [comment]
I fixed it with:
# Import
from python_aternos import Client, AternosConnect

# Create AternosConnect object
atconn = AternosConnect()
atconn.session.cookies['ATERNOS_SESSION'] = '9b6C33MDD6fu3ZUbKQF8uyA8SSL42JgYBr1tqVEqWJoUZ79LlCintaIq39JBjjS4BJHabt0xLx2EzmpQ9BOECtoPpz1JMrCtmzqw'

# Create Client object
atclient = Client(atconn)

# Get servers list
servs = atclient.list_servers()
print(servs)



and now i get:
Traceback (most recent call last):
  File "E:\5B5P Bot\5B5P Bot.py", line 12, in <module>
    servs = atclient.list_servers()
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\python_aternos\atclient.py", line 326, in list_servers
    self.refresh_servers(servers)
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\python_aternos\atclient.py", line 352, in refresh_servers
    srv = AternosServer(servid, self.atconn)
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\python_aternos\atserver.py", line 69, in __init__
    self.fetch()
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\python_aternos\atserver.py", line 74, in fetch
    servreq = self.atserver_request(
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\python_aternos\atserver.py", line 231, in atserver_request
    return self.atconn.request_cloudflare(
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\python_aternos\atconnect.py", line 279, in request_cloudflare
    req.raise_for_status()
  File "C:\Users\asusd\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://aternos.org/panel/ajax/status.php?TOKEN=&SEC=
[Finished in 1.0s]

**Comment by AndrexYT** [comment]
@lusm554 @DarkCat09 @RuochenFu21 @ghrlt Please someone fix it.

**Comment by AndrexYT** [comment]
Oh, i fixed it, just downgraded version, its all.
